declare module "$amplify/env/mintPass" { export const env: any; }
declare module "$amplify/env/attestPass" { export const env: any; }
declare module "$amplify/env/createGToken" { export const env: any; }
declare module "$amplify/env/createIssuerProfile" { export const env: any; }
declare module "$amplify/env/updateIssuerProfile" { export const env: any; }
declare module "$amplify/env/createRWATokenProfile" { export const env: any; }
declare module "$amplify/env/updateRWATokenProfile" { export const env: any; }
declare module "$amplify/env/deleteRWATokenProfile" { export const env: any; }
declare module "$amplify/env/postAnnouncement" { export const env: any; }
